### ISSUE TITLE
Sidebar issue

### ISSUE THREAD

**Issue by captvansciencypants** [JHay0112/lcadide#19]
Putting components in the area occupied by the sidebar when the sidebar slides out causes issues

**Comment by JHay0112** [comment]
Here is an example of a component appearing over the slid-out sidebar
![image](https://user-images.githubusercontent.com/29882279/217962237-fe8df85b-53da-4a37-8baa-a8ceb3042b5b.png)

The desired behaviour is that the component stay in the same place but that the sidebar appears on top of the component instead of the other way around.

**Comment by JHay0112** [comment]
This appears to have been inadvertenly fixed by def29dd, this may be closed once the wire branch is merged.

**Comment by JHay0112** [comment]
Wire branch has been closed. This problem has been fixed.
